# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - turntable_trajectory_controller
    - turntable_forward_position_controller

  turntable_trajectory_controller:
    type: FollowJointTrajectory
    joints:
      - disc_joint
    action_ns: follow_joint_trajectory
    default: true
