# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    turntable_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    turntable_scaled_trajectory_controller:
      type: ur_controllers/ScaledJointTrajectoryController


    turntable_forward_position_controller:
      type: position_controllers/JointGroupPositionController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

turntable_trajectory_controller:
  ros__parameters:
    joints:
      - disc_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
turntable_scaled_trajectory_controller:
  ros__parameters:
    joints:
      - disc_joint
turntable_forward_position_controller:
  ros__parameters:
    joints:
      - disc_joint