controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    turntable_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    turntable_forward_position_controller:
      type: position_controllers/JointGroupPositionController

# ====== CONTROLLER CONFIGURATIONS ======

turntable_trajectory_controller:
  ros__parameters:
    joints:
      - disc_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    allow_nonzero_velocity_at_trajectory_end: false

turntable_forward_position_controller:
  ros__parameters:
    joints:
      - disc_joint
    interface_name: position
    state_publish_rate: 50.0
    action_monitor_rate: 20.0